version: '3'
services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./backend:/app


    # depends_on:
    #   - db

  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "8080:3000" # Mapping Vue app port
    volumes:
      - ./frontend:/app



#   db:
#     image: mysql:5.7
#     container_name: mysql_db
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: book_inventory
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
